### ISSUE TITLE
Gettext and ex_i18n integration

### ISSUE THREAD

**Issue by kipcole9** [elixir-cldr/cldr_messages#5]
@tmbb, @maennchen,

Having updated docs and tests I think that an update to `ex_cldr_messages` is ready to be published. It includes:

1. Support for [ex_i18n](https://github.com/tmbb/ex_i18n). 
2. Support for the [gettext 0.19](https://hex.pm/packages/gettext/0.19)'s [interpolation module](https://hexdocs.pm/gettext/Gettext.html#module-backend-configuration) and therefore first-class-citizen status in the `gettext` ecosystem.

### What's missing

* Documentation on how to integrate with `ex_i18n`.  @tmbb, is this still a project you plan to publish?  Any chance of collaboration on some documentation on how to integrate and for workflow?

### An ask

May I ask you both to review and comment?  

### Steps before publishing

* Build a [livebook](https://github.com/livebook-dev/livebook) example of how to do message formatting

**Comment by tmbb** [comment]
I still plan on publishing that eventually, but I haven't had much time lately. The project is meant to me completely independent of CLDR release plan,so go ahead with your normal publishing schedule.

**Comment by maennchen** [comment]
@kipcole9 Awesome! (Sorry for only replying now, I was on vacation)

I would do some minor additions:

* We should include the instructions from the README abotu `Gettext` in the `Cldr.Gettext.Interpolation` moduledocs.
* The file path for the `Cldr.Gettext.Interpolation` module should be `lib/cldr/gettext/interpolation.ex` and not `lib/cldr/gettext/interpolate.ex`.
* The `CHANGELOG` should probably mention the new feature.

**Comment by maennchen** [comment]
@kipcole9 There also seems to be an issue with passing through the backend correctly:

`gettext("Message {number}", number: 7)` should pick up the number formatter backend from the interpolation module, but it raises `Cldr.NoDefaultBackendError`.

**Comment by maennchen** [comment]
@kipcole9 Another issue with the compilation order:

```
== Compilation error in file lib/hygeia_gettext.ex ==
** (exit) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom

        :erlang.binary_to_existing_atom("ordering", :utf8)
        (ex_cldr_messages 0.13.0) lib/cldr/messages/backend.ex:158: Cldr.Message.Backend.validate_binding!/2
        (ex_cldr_messages 0.13.0) lib/cldr/messages/backend.ex:206: Cldr.Message.Backend.prewalk/2
        expanding macro: HygeiaCldr.GettextInterpolation.compile_interpolate/3
        lib/hygeia_gettext.ex:1: HygeiaGettext.T_it_default.it_default_lgettext/3
```

The Gettext files contain the message `%{ordering} jab date`. Since the gettext module is compiled before the source code itself, the binding name atom, does not yet exist.

Because of this, we should probably do two changes:

* Use `String.to_atom` (not existing) when compiling the messages via the interpolation module
* If the message is interpolated at runtime and the name still does not exist, catch the error and make it more meaningful to the user.

**Comment by maennchen** [comment]
@kipcole9 Did you see my comments? Can I be of any assistance?

**Comment by kipcole9** [comment]
Sorry for the delay, day job been getting in the way this last week :-)

As of commit [e100ac3]( https://github.com/elixir-cldr/cldr_messages/commit/e100ac3922bb951477b76445803b94963792100c) the compile-time bindings are now converted with `String.to_atom/1` as you propose.

The runtime-bindings return an error consistent with the `Gettext.Interpolation` behaviour being a `{:missing_binding, message, unknown_bindings}` tuple.

Does this resolve the issue you identified?

**Comment by kipcole9** [comment]
As of commit [a2550a5](https://github.com/elixir-cldr/cldr_messages/commit/a2550a5c1bb84cb1b7aab9db5df3ec614a4aa825) the following have been address:

1. File name for `Cldr.Gettext.Interpolation` has been fixed
2. Add module docs for `Cldr.Gettext.Interpolation`
3. Derive the CLDR backend module (don't use the default backend which may not exist)

Let me know if you spot anything else?

**Comment by maennchen** [comment]
@kipcole9 Great, thanks. 😊 I’ll try again to implement it in our app and will share the outcome.
